// Requested additions; a visible entry is not a playable exam unless its bank ID exists.
window.OMNITECH_TRACKS.push(
 {"name":"Microsoft AZ-700 — Azure Network Engineer","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["AZ-700","Microsoft AZ-700 — Azure Network Engineer","az-700"]]},
 {"name":"Microsoft SC-900 — Security, Compliance, and Identity Fundamentals","requirement":"امتحان مستقل","items":[["SC-900","SC-900","sc-900"]]},
 {"name":"Microsoft SC-200 — Security Operations Analyst","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["SC-200","Microsoft SC-200 — Security Operations Analyst","sc-200"]]},
 {"name":"Microsoft SC-300 — Identity and Access Administrator","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["SC-300","Microsoft SC-300 — Identity and Access Administrator","sc-300"]]},
 {"name":"Microsoft SC-100 — Cybersecurity Architect","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["SC-100","Microsoft SC-100 — Cybersecurity Architect","sc-100"]]},
 {"name":"Microsoft SC-401 — Information Security Administrator","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["SC-401","Microsoft SC-401 — Information Security Administrator","sc-401"]]},
 {"name":"Microsoft AZ-900 — Azure Fundamentals","requirement":"امتحان مستقل","items":[["AZ-900","AZ-900","az-900"]]},
 {"name":"Microsoft AZ-104 — Azure Administrator","requirement":"امتحان مستقل","items":[["AZ-104","AZ-104","az-104"]]},
 {"name":"Microsoft AZ-305 — Azure Solutions Architect","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["AZ-305","Microsoft AZ-305 — Azure Solutions Architect","az-305"]]},
 {"name":"AWS Certified Cloud Practitioner","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","AWS Certified Cloud Practitioner","aws-cloud-practitioner"]]},
 {"name":"AWS Certified Solutions Architect – Associate","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","AWS Certified Solutions Architect – Associate","aws-saa"]]},
 {"name":"AWS Certified Solutions Architect – Professional","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","AWS Certified Solutions Architect – Professional","aws-sap"]]},
 {"name":"AWS Certified CloudOps Engineer – Associate","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","AWS Certified CloudOps Engineer – Associate","aws-cloudops"]]},
 {"name":"AWS Certified Developer – Associate","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","AWS Certified Developer – Associate","aws-developer"]]},
 {"name":"AWS Certified DevOps Engineer – Professional","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","AWS Certified DevOps Engineer – Professional","aws-devops"]]},
 {"name":"AWS Certified Security – Specialty","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","AWS Certified Security – Specialty","aws-security-specialty"]]},
 {"name":"AWS Certified Advanced Networking – Specialty","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","AWS Certified Advanced Networking – Specialty","aws-networking-specialty"]]},
 {"name":"Google Cloud Digital Leader","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","Google Cloud Digital Leader","google-digital-leader"]]},
 {"name":"Google Associate Cloud Engineer","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","Google Associate Cloud Engineer","google-ace"]]},
 {"name":"Google Professional Cloud Architect","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","Google Professional Cloud Architect","google-pca"]]},
 {"name":"Google Professional Cloud Network Engineer","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","Google Professional Cloud Network Engineer","google-pcne"]]},
 {"name":"Google Professional Cloud Security Engineer","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","Google Professional Cloud Security Engineer","google-pcse"]]},
 {"name":"Fortinet NSE — Secure Networking","requirement":"مسار متعدد الامتحانات","items":[["NSE 4 FortiOS 7.6 Administrator","NSE 4 FortiOS 7.6 Administrator","nse4-fortios-76"],["المسار","امتحانات تخصص أخرى ضمن المسار"]]},
 {"name":"Fortinet NSE — Security Operations","requirement":"مسار يضم امتحانات تخصصية؛ حدّد الامتحان الرسمي عند إعداد البنك","items":[["المسار","Fortinet NSE — Security Operations"]]},
 {"name":"Fortinet NSE — SASE","requirement":"مسار يضم امتحانات تخصصية؛ حدّد الامتحان الرسمي عند إعداد البنك","items":[["المسار","Fortinet NSE — SASE"]]},
 {"name":"HPE Juniper JNCIA-Junos","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","HPE Juniper JNCIA-Junos","jncia-junos"]]},
 {"name":"HPE Juniper JNCIS-ENT","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","HPE Juniper JNCIS-ENT","jncis-ent"]]},
 {"name":"HPE Juniper JNCIP-ENT","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","HPE Juniper JNCIP-ENT","jncip-ent"]]},
 {"name":"HPE Juniper JNCIE-ENT","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","HPE Juniper JNCIE-ENT",null,"lab"]]},
 {"name":"HPE Juniper JNCIS-SP","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","HPE Juniper JNCIS-SP","jncis-sp"]]},
 {"name":"HPE Juniper JNCIP-SP","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","HPE Juniper JNCIP-SP","jncip-sp"]]},
 {"name":"HPE Juniper JNCIE-SP","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","HPE Juniper JNCIE-SP",null,"lab"]]},
 {"name":"HPE Juniper JNCIA-Cloud","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","HPE Juniper JNCIA-Cloud","jncia-cloud"]]},
 {"name":"Palo Alto Networks — Network Security","requirement":"امتحانات المسار","items":[["NGFW Engineer","NGFW Engineer","ngfw-engineer"],["المسار","امتحانات تخصص أخرى ضمن المسار"]]},
 {"name":"Palo Alto Networks — Security Operations","requirement":"مسار يضم امتحانات تخصصية؛ حدّد الامتحان الرسمي عند إعداد البنك","items":[["المسار","Palo Alto Networks — Security Operations"]]},
 {"name":"Palo Alto Networks — Prisma Access","requirement":"مسار يضم امتحانات تخصصية؛ حدّد الامتحان الرسمي عند إعداد البنك","items":[["المسار","Palo Alto Networks — Prisma Access"]]},
 {"name":"Palo Alto Networks — Prisma Cloud","requirement":"مسار يضم امتحانات تخصصية؛ حدّد الامتحان الرسمي عند إعداد البنك","items":[["المسار","Palo Alto Networks — Prisma Cloud"]]},
 {"name":"Check Point CCSA","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","Check Point CCSA","check-point-ccsa"]]},
 {"name":"Check Point CCSE","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","Check Point CCSE","check-point-ccse"]]},
 {"name":"ISC2 Certified in Cybersecurity — CC","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","ISC2 Certified in Cybersecurity — CC","isc2-cc"]]},
 {"name":"ISC2 SSCP","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","ISC2 SSCP","isc2-sscp"]]},
 {"name":"ISC2 CISSP","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","ISC2 CISSP","isc2-cissp"]]},
 {"name":"ISC2 CCSP","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","ISC2 CCSP","isc2-ccsp"]]},
 {"name":"ISC2 CGRC","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","ISC2 CGRC","isc2-cgrc"]]},
 {"name":"EC-Council CEH","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","EC-Council CEH","ec-ceh"]]},
 {"name":"EC-Council CND","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","EC-Council CND","ec-cnd"]]},
 {"name":"EC-Council CHFI","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","EC-Council CHFI","ec-chfi"]]},
 {"name":"GIAC GSEC","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","GIAC GSEC","giac-gsec"]]},
 {"name":"GIAC GCIH","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","GIAC GCIH","giac-gcih"]]},
 {"name":"GIAC GCIA","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","GIAC GCIA","giac-gcia"]]},
 {"name":"GIAC GPEN","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","GIAC GPEN","giac-gpen"]]},
 {"name":"GIAC GWAPT","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","GIAC GWAPT","giac-gwapt"]]},
 {"name":"GIAC GCFA","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","GIAC GCFA","giac-gcfa"]]},
 {"name":"GIAC GCLD","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","GIAC GCLD","giac-gcld"]]},
 {"name":"GIAC GPCS","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","GIAC GPCS","giac-gpcs"]]},
 {"name":"GIAC GCFR","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","GIAC GCFR","giac-gcfr"]]},
 {"name":"OffSec OSCP","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","OffSec OSCP",null,"lab"]]},
 {"name":"OffSec OSEP","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","OffSec OSEP",null,"lab"]]},
 {"name":"OffSec OSWE","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","OffSec OSWE",null,"lab"]]},
 {"name":"OffSec OSED","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","OffSec OSED",null,"lab"]]},
 {"name":"ISACA CISM","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","ISACA CISM","isaca-cism"]]},
 {"name":"ISACA CISA","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","ISACA CISA","isaca-cisa"]]},
 {"name":"ISACA CRISC","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","ISACA CRISC","isaca-crisc"]]},
 {"name":"Cloud Security Alliance CCSK","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Cloud Security Alliance CCSK","csa-ccsk"]]},
 {"name":"Huawei HCIA-Datacom","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Huawei HCIA-Datacom","hcia-datacom"]]},
 {"name":"Huawei HCIP-Datacom","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Huawei HCIP-Datacom","hcip-datacom"]]},
 {"name":"Huawei HCIE-Datacom","requirement":"تقييم نظري للجزء التحريري؛ العملي يحتاج مختبرًا منفصلًا","items":[["الامتحان","Huawei HCIE-Datacom","hcie-datacom"]]},
 {"name":"Huawei HCIA-Security","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Huawei HCIA-Security","hcia-security"]]},
 {"name":"Huawei HCIP-Security","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Huawei HCIP-Security","hcip-security"]]},
 {"name":"Huawei HCIE-Security","requirement":"تقييم نظري للجزء التحريري؛ العملي يحتاج مختبرًا منفصلًا","items":[["الامتحان","Huawei HCIE-Security","hcie-security"]]},
 {"name":"Huawei HCIA-Cloud Computing","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Huawei HCIA-Cloud Computing","hcia-cloud"]]},
 {"name":"Huawei HCIP-Cloud Computing","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Huawei HCIP-Cloud Computing","hcip-cloud"]]},
 {"name":"Huawei HCIE-Cloud Computing","requirement":"تقييم نظري للجزء التحريري؛ العملي يحتاج مختبرًا منفصلًا","items":[["الامتحان","Huawei HCIE-Cloud Computing","hcie-cloud"]]},
 {"name":"MikroTik MTCNA","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","MikroTik MTCNA","mikrotik-mtcna"]]},
 {"name":"MikroTik MTCRE","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","MikroTik MTCRE","mikrotik-mtcre"]]},
 {"name":"MikroTik MTCINE","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","MikroTik MTCINE","mikrotik-mtcine"]]},
 {"name":"MikroTik MTCWE","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","MikroTik MTCWE","mikrotik-mtcwe"]]},
 {"name":"MikroTik MTCTCE","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","MikroTik MTCTCE","mikrotik-mtctce"]]},
 {"name":"MikroTik MTCSE","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","MikroTik MTCSE","mikrotik-mtcse"]]},
 {"name":"CNCF KCNA","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","CNCF KCNA","cncf-kcna"]]},
 {"name":"CNCF CKA","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","CNCF CKA",null,"lab"]]},
 {"name":"CNCF CKAD","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","CNCF CKAD",null,"lab"]]},
 {"name":"CNCF CKS","requirement":"تقييم عملي يحتاج بيئة مختبر","items":[["LAB","CNCF CKS",null,"lab"]]},
 {"name":"Oracle OCI Foundations","requirement":"تقييم نظري قيد إعداد بنك مستقل","items":[["الامتحان","Oracle OCI Foundations","oracle-oci-foundations"]]},
 {"name":"Oracle OCI Architect Associate","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Oracle OCI Architect Associate","oracle-oci-architect-associate"]]},
 {"name":"Oracle OCI Architect Professional","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Oracle OCI Architect Professional","oracle-oci-architect-professional"]]},
 {"name":"Oracle OCI Networking","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Oracle OCI Networking","oracle-oci-networking"]]},
 {"name":"Oracle OCI Security","requirement":"اختبار تشخيصي نظري مستقل","items":[["الامتحان","Oracle OCI Security","oracle-oci-security"]]}
);
