const $=id=>document.getElementById(id),exams=(window.OMNITECH_EXAMS||[]).filter(e=>e.questions.length>=40);let active=null,selectedExam=null,presented=[],answers=[],position=0,tick=null,end=0,submitted=false;
const codeFor=id=>window.OMNITECH_ACCESS_CODES?.[id];
const lockKey=id=>`omnitech_completed_${codeFor(id)}_${id}`;
const show=id=>{for(const name of ['auth','exam','result'])$(name).classList.toggle('hidden',name!==id)};
function resetSelection(){selectedExam=null;$('code').value='';$('authStatus').textContent='';$('codePanel').classList.add('hidden');document.querySelectorAll('#publicExams .selected').forEach(card=>card.classList.remove('selected'))}
function choose(exam,card){resetSelection();selectedExam=exam;card.classList.add('selected');$('selectedExamName').textContent=`كود امتحان ${exam.name}`;$('codePanel').classList.remove('hidden');if(localStorage.getItem(lockKey(exam.id)))$('authStatus').textContent='انتهت محاولتك لهذا الامتحان على المتصفح نفسه.';$('code').focus()}
const publicExams=$('publicExams');
for(const [index,track] of (window.OMNITECH_TRACKS||[]).entries()){
 const section=document.createElement('details'),heading=document.createElement('summary'),hint=document.createElement('small'),grid=document.createElement('div');
 section.className='track';section.open=index===0;heading.textContent=track.name;hint.textContent=track.requirement;heading.append(hint);grid.className='grid';
 for(const [number,label,id,format] of track.items){
  const exam=exams.find(e=>e.id===id),card=document.createElement(exam?'button':'div'),badge=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small');
  card.className='card'+(exam?'':' pending');badge.className='badge';badge.textContent=number;name.textContent=label;
  meta.textContent=exam?`${exam.questions.length} سؤال تدريبي · ${exam.minutes} دقيقة${exam.coverage?' · '+exam.coverage:''}`:(format==='lab'?'امتحان عملي · يحتاج لاب مستقل':'بنك الأسئلة قيد الإعداد');
  card.append(badge,name,meta);if(exam){card.type='button';card.onclick=()=>{choose(exam,card);$('codePanel').scrollIntoView({behavior:'smooth',block:'center'})}}grid.append(card);
 }
 section.append(heading,grid);publicExams.append(section);
}
const trackSections=[...publicExams.children];
function filterTracks(){const query=$('trackSearch').value.trim().toLocaleLowerCase();let visible=0;for(const [index,section] of trackSections.entries()){const track=window.OMNITECH_TRACKS[index];const searchable=[track.name,...track.items.flatMap(item=>item.slice(0,2))].join(' ').toLocaleLowerCase();section.hidden=!searchable.includes(query);if(!section.hidden)visible++}if(query&&visible===1)trackSections.find(section=>!section.hidden).open=true;$('trackCount').textContent=`${visible} شهادة أو مسار من ${trackSections.length} · ${exams.length} اختبار تدريبي جاهز`}
$('trackSearch').addEventListener('input',filterTracks);filterTracks();
$('cancelSelection').onclick=resetSelection;
$('accessForm').addEventListener('submit',event=>{event.preventDefault();if(!selectedExam)return;const expected=codeFor(selectedExam.id);if(!expected||$('code').value!==expected){$('authStatus').textContent='الكود لا يخص هذا الامتحان. راجع الكود أو اختر الامتحان الصحيح.';return}if(localStorage.getItem(lockKey(selectedExam.id))){$('authStatus').textContent='انتهت محاولتك لهذا الامتحان على المتصفح نفسه.';return}$('authStatus').textContent='';start(selectedExam)});
function shuffledChoices(q){const choices=q.options.map((label,index)=>({label,index}));for(let i=choices.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]]}return {...q,choices}}
function start(exam){if(localStorage.getItem(lockKey(exam.id))){$('authStatus').textContent='تم إنهاء هذا الامتحان على هذا المتصفح.';show('auth');return}active=exam;presented=exam.questions.map(shuffledChoices);for(let i=presented.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[presented[i],presented[j]]=[presented[j],presented[i]]}answers=Array(presented.length).fill(null);position=0;submitted=false;end=Date.now()+exam.minutes*60000;$('examName').textContent=exam.name;$('progress').max=presented.length;$('progress').value=0;render();show('exam');clearInterval(tick);tick=setInterval(updateTimer,1000);updateTimer()}
function render(){const q=presented[position],form=$('examForm');form.replaceChildren();const field=document.createElement('fieldset');field.className='question';const legend=document.createElement('legend');legend.textContent=`سؤال ${position+1} من ${presented.length} · ${q.topic}\n${q.text}`;field.append(legend);q.choices.forEach((choice,index)=>{const label=document.createElement('label');label.className='option';const input=document.createElement('input');input.type='radio';input.name='answer';input.value=index;input.checked=answers[position]===choice.index;input.onchange=()=>{answers[position]=choice.index;updateProgress()};label.append(input,document.createTextNode(choice.label));field.append(label)});form.append(field);$('prev').disabled=position===0;$('next').disabled=position===presented.length-1;$('next').textContent=position===presented.length-2?'السؤال الأخير':'التالي';updateProgress()}
function updateProgress(){const count=answers.filter(value=>value!==null).length;$('progress').value=count;const nav=$('questionNav');nav.replaceChildren(...presented.map((_,index)=>{const btn=document.createElement('button');btn.type='button';btn.textContent=index+1;btn.className=(answers[index]!==null?'answered ':'')+(index===position?'current':'');btn.title=`سؤال ${index+1}${answers[index]!==null?' · تمت الإجابة':''}`;btn.onclick=()=>{position=index;render();window.scrollTo({top:$('exam').offsetTop-15,behavior:'smooth'})};return btn}));$('submitExam').textContent=`تسليم الاختبار (${count}/${presented.length})`}
function updateTimer(){const seconds=Math.max(0,Math.ceil((end-Date.now())/1000));$('timer').textContent=`الوقت المتبقي: ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;if(!seconds)submit(true)}
$('prev').onclick=()=>{position--;render()};$('next').onclick=()=>{position++;render()};$('examForm').onsubmit=event=>event.preventDefault();$('submitExam').onclick=()=>submit(false);
function submit(automatic){if(submitted)return;const unanswered=answers.filter(value=>value===null).length;if(!automatic&&unanswered&&!confirm(`باقي ${unanswered} سؤال بدون إجابة. هل تريد تسليم الاختبار؟`))return;submitted=true;clearInterval(tick);localStorage.setItem(lockKey(active.id),new Date().toISOString());const details=presented.map((q,i)=>({topic:q.topic,correct:answers[i]===q.answer,why:q.why,answer:q.options[q.answer],selected:answers[i]===null?'بدون إجابة':q.options[answers[i]],text:q.text}));const score=details.filter(item=>item.correct).length;const result=$('result');result.replaceChildren();const heading=document.createElement('h2');heading.textContent=`نتيجتك في ${active.name}: ${score} من ${details.length}`;const note=document.createElement('p');note.textContent=automatic?'انتهى الوقت وتم تصحيح الإجابات المسجلة.':'هذه نتيجة تدريبية، وليست درجة الامتحان الرسمي أو توقعًا مضمونًا للنجاح.';const readiness=document.createElement('p');const percent=Math.round(score/details.length*100);readiness.textContent=`تقديرك التدريبي: ${percent}% · ${percent>=85?'أداء قوي في هذه الأسئلة':percent>=70?'تحتاج مراجعة بعض المحاور':'راجع المحاور الأساسية قبل حجز الامتحان'}. هذا التقدير ليس حد نجاح رسميًا.`;result.append(heading,note,readiness);const groups=[...new Set(details.map(d=>d.topic))],table=document.createElement('table');table.className='domain-table';const head=document.createElement('tr');for(const cell of ['المحور','الصحيح','الإجمالي']){const th=document.createElement('th');th.textContent=cell;head.append(th)}table.append(head);for(const group of groups){const values=details.filter(d=>d.topic===group),row=document.createElement('tr');for(const cell of [group,values.filter(d=>d.correct).length,values.length]){const td=document.createElement('td');td.textContent=cell;row.append(td)}table.append(row)}result.append(table);const disclosure=document.createElement('details'),summary=document.createElement('summary');summary.textContent='مراجعة الإجابات والتفسيرات';disclosure.append(summary);details.forEach((item,i)=>{const div=document.createElement('div');div.className='review-item';const strong=document.createElement('strong');strong.textContent=`${i+1}. ${item.text} — ${item.correct?'صحيح':'يحتاج مراجعة'}`;const explain=document.createElement('p');explain.textContent=`إجابتك: ${item.selected} · الإجابة الصحيحة: ${item.answer}. ${item.why}`;div.append(strong,explain);disclosure.append(div)});result.append(disclosure);const back=document.createElement('button');back.type='button';back.textContent='إنهاء والخروج إلى صفحة الكود';back.onclick=finish;result.append(back);active=null;presented=[];answers=[];show('result');window.scrollTo({top:0,behavior:'smooth'})}
$('back').onclick=()=>{if(!confirm('هل تريد مغادرة الاختبار؟ لن تُحفظ إجاباتك في هذه النسخة.'))return;clearInterval(tick);active=null;presented=[];answers=[];resetSelection();show('auth')};

function finish(){clearInterval(tick);active=null;presented=[];answers=[];resetSelection();$('authStatus').textContent='انتهت المحاولة على هذا المتصفح.';show('auth');history.replaceState(null,'',location.pathname)}
