// Original educational MCQs aligned to Microsoft AZ-104 skill areas as of April 2026.
const AZ104 = [
['Identity and governance','تريد السماح لفريق بقراءة موارد مجموعة موارد واحدة دون تعديل. ما التعيين؟','Reader على Resource group','Owner على Subscription','Global Administrator','Contributor على Management group','الدور والنطاق يجب أن يقتصرا على الحاجة.'],
['Identity and governance','مسؤول يحتاج إدارة موارد VM في مجموعة واحدة دون منح صلاحية الوصول للمستخدمين. ما الدور؟','Virtual Machine Contributor في النطاق','Owner على الاشتراك','User Access Administrator','Global Reader فقط','الدور المختص يتيح إدارة VM في النطاق المحدد.'],
['Identity and governance','تريد إدارة عدة اشتراكات بسياسة Azure Policy واحدة. أين تربطها؟','Management group فوق الاشتراكات','VM واحدة','Storage container','Network interface','تطبيق السياسة على مجموعة إدارة يرثه نطاق الاشتراكات.'],
['Identity and governance','تحتاج منع حذف Resource group بالغلط دون منع تعديل مواردها. ما القفل؟','CanNotDelete','ReadOnly','DeleteAll','NoLock','CanNotDelete يمنع الحذف لكنه لا يمنع التعديل المسموح.'],
['Identity and governance','Policy تمنع إنشاء Public IP جديد. ما effect المناسب؟','Deny','Audit فقط','Disabled','Append فقط','Deny يرفض العمليات غير المتوافقة.'],
['Identity and governance','Policy تعرض موارد بلا Tag مطلوب دون منع نشرها. ما effect؟','Audit','Deny','Delete','Lock','Audit يسجل عدم الامتثال دون رفض العملية.'],
['Identity and governance','مستخدم خارجي يحتاج تعاونًا في tenant دون حساب داخلي دائم. ماذا تستخدم؟','Microsoft Entra B2B guest','حساب Owner مشترك','عنوان IP ثابت فقط','خدمة DNS','الضيف يتيح الوصول المصرح مع هوية خارجية.'],
['Identity and governance','تريد إتاحة إعادة تعيين كلمة المرور للمستخدمين بعد التحقق. ما الميزة؟','SSPR','SNAT','Bicep','Azure Files','SSPR يسمح بالاستعادة الذاتية وفق سياسة التحقق.'],
['Identity and governance','كيف تعرف مصدر صلاحية مستخدم على VM؟','افحص role assignments المباشرة والموروثة على النطاقات','افحص حجم القرص','افحص tags فقط','افحص DNS zone','قد ترث الأدوار من مجموعة الموارد أو الاشتراك.'],
['Identity and governance','تريد معرفة تكلفة موارد مشروعين في اشتراك واحد. ما الوسيلة؟','Tags وCost Management','VNet peering','Azure Bastion','NSG','الوسوم تدعم تجميع التكاليف بحسب المشروع.'],
['Identity and governance','متى تستخدم budget alert؟','لتنبيه المسؤول عند اقتراب الإنفاق من حد معين','لمنع كل الاستهلاك تلقائيًا دائمًا','لتشفير blobs','لإنشاء VM','التنبيه يخبر عن التكلفة ولا يوقف الخدمات تلقائيًا.'],
['Identity and governance','تريد منح مجموعة موظفين الدور نفسه وإدارة العضوية مركزيًا. ما الأفضل؟','تعيين RBAC لمجموعة Entra','تعيين كل مستخدم Owner','مشاركة حساب','فتح الواجهة للعامة','التعيين للمجموعة يسهل إدارة الوصول.'],
['Storage','تريد صلاحية تحميل Blob محدد لمدة ساعتين دون كشف مفتاح الحساب. ما الخيار؟','SAS محدد النطاق والمدة','مفتاح حساب منشور','Public anonymous access لكل الحاوية','Owner على الاشتراك','SAS يمنح وصولًا محدودًا زمنًا وموارد وصلاحية.'],
['Storage','مفتاح storage account تسرب. ما أول مسار معالجة مناسب؟','تدوير المفتاح وتحديد أثر الاستخدام','إضافة Tag','إلغاء logging','رفع MTU','تدوير المفتاح يوقف استخدام الاعتماد المكشوف.'],
['Storage','تحتاج تقييد وصول حساب التخزين لشبكات افتراضية مختارة. ما الضابط؟','Storage firewall مع قواعد شبكات','Azure Advisor فقط','VM Scale Set','Azure DNS','قواعد الشبكة تقيد الوصول لنقاط الخدمة.'],
['Storage','ما الفارق بين Private Endpoint وService Endpoint للتخزين؟','Private Endpoint يعطي IP خاصًا للخدمة داخل VNet','Service Endpoint ينشئ IP خاصًا للخدمة داخل VNet','كلاهما يغير كلمة مرور الحساب','لا يحتاجان DNS','Private Endpoint يستخدم واجهة وعنوانًا خاصين للخدمة.'],
['Storage','تحتاج تكرار البيانات إلى منطقة ثانوية مع قراءات من النسخة الثانوية. ما الخيار؟','RA-GRS','LRS','ZRS فقط','Temporary disk','RA-GRS يضيف read access للمنطقة الثانية.'],
['Storage','ملف Azure Files حُذف عرضًا. أي ميزة تهيئ مسبقًا؟','Soft delete للـfile share','NSG','Bicep فقط','Azure Bastion','Soft delete يتيح استعادة المشاركات ضمن فترة الاحتفاظ.'],
['Storage','تريد استعادة محتوى Blob قديم بعد استبداله. ما الميزة؟','Blob versioning','VNet peering','LACP','Activity log فقط','Versioning يحتفظ بإصدارات الكائنات.'],
['Storage','صور لا تُفتح بعد 90 يومًا وتريد خفض كلفة تخزينها تلقائيًا. ما الخيار؟','Lifecycle management rule تنقل إلى tier أبرد','استبدال DNS','رفع حجم VM','تعطيل نسخ التخزين','قواعد lifecycle تغير طبقة البيانات بمرور الوقت.'],
['Storage','تنقل بيانات كبيرة بين مخزنين عبر سطر الأوامر. ما الأداة؟','AzCopy','Azure Bastion','NSG','Service Health','AzCopy مناسب لنسخ بيانات Azure Storage.'],
['Storage','تحتاج مشاركة SMB مع مصادقة هوية مؤسسية. ما الخدمة؟','Azure Files مع identity-based access','Blob anonymous public','Azure DNS','Azure Load Balancer','Azure Files يدعم وصول الملفات وإعدادات الهوية.'],
['Compute','كيف تنشر 20 VM بإعداد متكرر قابل للمراجعة؟','Bicep أو ARM template','نقر يدوي 20 مرة','نسخ لقطة شاشة','تعديل DNS فقط','التعريف التصريحي يتيح تكرار النشر.'],
['Compute','ما الفرق بين availability set وavailability zones؟','set يوزع ضمن مركز بيانات منطقيا وzones تفصل مواقع داخل المنطقة','كلاهما IP عام','zones تضمن عدم الحاجة للنسخ','set يشفر البيانات','zones تعطي عزلًا مكانيًا أوسع.'],
['Compute','حمل VM يستهلك RAM باستمرار. ما الإجراء الإداري المباشر؟','Resize إلى SKU بسعة مناسبة بعد التقييم','زيادة DNS TTL','تغيير NSG','إضافة Tag','اختيار حجم VM يلائم احتياج الذاكرة.'],
['Compute','تريد تشفير البيانات في ذاكرة host المخصصة لـVM وقرصها أثناء المعالجة على المضيف. ما الميزة المرتبطة؟','Encryption at host','ReadOnly lock','Azure DNS','Application Insights','تشفير المضيف يحمي البيانات على مضيف VM.'],
['Compute','تطبيق ينشر إصدارات على App Service وتريد swap قبل الإطلاق. ما الميزة؟','Deployment slots','Azure Files snapshot','Management group','Private DNS zone','الـslots تتيح اختبار إصدار ثم تبديل المواقع.'],
['Compute','تطبيق App Service يحتاج توسيع عدد النسخ تلقائيًا حسب CPU. أين تضبط؟','Autoscale لخطة App Service المناسبة','Azure Policy audit','NSG inbound','Tag','التوسع الأفقي يزيد مثيلات الخدمة عند الحمل.'],
['Compute','لماذا تختار App Service plan أعلى لتطبيق يحتاج مزايا متقدمة؟','الخطة تحدد الموارد والقدرات المتاحة','الخطة تعين أدوار RBAC','الخطة تحدد VNet IP للمكتب','الخطة تدير DNS الداخلي','خطة الاستضافة تتحكم بالموارد والميزات.'],
['Compute','تحتاج سجل صور حاويات خاصًا للمؤسسة. ما الخدمة؟','Azure Container Registry','Azure DNS','Azure Bastion','Azure Backup','ACR يخزن صور الحاويات ويديرها.'],
['Compute','مهمة حاوية قصيرة دون إدارة Kubernetes. ما الخدمة؟','Azure Container Instances','Azure Site Recovery','Azure Files','Azure Policy','ACI يشغل حاويات حسب الطلب دون إدارة orchestrator.'],
['Compute','تريد استضافة تطبيقات حاوية مع توسع ووظائف تطبيقية مدارة. ما الخدمة؟','Azure Container Apps','Azure Disk Snapshot','Azure DNS','NSG','Container Apps منصة مدارة للتطبيقات المبنية على الحاويات.'],
['Compute','ما الذي يتحكم في حجم القرص الدائم لآلة Azure VM؟','Managed disk SKU وحجمه','Tag المشروع','NTP','Azure DNS','الأقراص المدارة تحدد الأداء والسعة وفق SKU.'],
['Compute','تريد نسخ VM إلى اشتراك آخر؛ ما أول ما تتحقق منه؟','دعم نقل نوع المورد والتبعيات والصلاحيات في الهدف','اسم الشخص الذي أنشأ Tag','حجم الشاشة','قناة Wi-Fi','النقل يعتمد على قيود الموارد والتبعيات والنطاقات.'],
['Networking','جهازان في VNets منفصلتين يحتاجان اتصالًا خاصًا منخفض التأخير. ما الخيار؟','VNet peering','Public blob','Azure Tags','App Service slots','peering يربط الشبكات عبر backbone Azure.'],
['Networking','بعد peering، VM لا تصل إلى خدمة عبر شبكة وسيطة ثالثة. ما التفسير الشائع؟','VNet peering ليس transitive افتراضيًا','كل peering يمنع ICMP','Azure لا يدعم routing','DNS دائماً السبب الوحيد','يلزم تصميم مرور عبر وسيط مع إعدادات مناسبة.'],
['Networking','تريد توجيه subnet عبر firewall افتراضي قبل الإنترنت. ما الأداة؟','User-defined route إلى virtual appliance','Tag','Soft delete','Activity log','UDR يحدد next hop للحركة.'],
['Networking','NSG على subnet يسمح TCP 443 لكن NSG على NIC يمنعه. ما النتيجة؟','يُمنع لأن السماح لازم في النطاقين','يُسمح دومًا بسبب subnet','تتحول الحركة إلى UDP','تُلغى قواعد NIC','يجب أن تسمح كل NSG مطبقة بالمرور.'],
['Networking','كيف تعرض القواعد النهائية المؤثرة على NIC؟','Effective security rules','Azure Advisor فقط','Storage Explorer','Bicep build','العرض الفعال يضم القواعد الموروثة على NIC وsubnet.'],
['Networking','تريد إدارة RDP/SSH للـVM دون Public IP مباشر. ما الخدمة؟','Azure Bastion','Azure Status','Blob versioning','Azure Functions','Bastion يوفر اتصال إدارة عبر البوابة دون عنوان عام للـVM.'],
['Networking','تطبيق يطلب عنوانًا خاصًا لخدمة PaaS داخل VNet. ما الخيار؟','Private Endpoint مع DNS صحيح','Public endpoint فقط','NSG فقط','Tag','Private Endpoint يخصص عنوان IP خاصًا للخدمة.'],
['Networking','تريد توزيع TCP على عدة VMs مع فحص صحة. ما الخدمة؟','Azure Load Balancer مع health probe','Azure Files','Azure Policy','Azure Key Vault','مسبار الصحة يحدد الأهداف الجاهزة.'],
['Networking','اسم خاص لخادم في VNet لا يُحل. ماذا تراجع؟','ربط Private DNS zone بالشبكة والسجلات','حجم VM','Tag','NTP فقط','ربط المنطقة وسجلاتها ضروري لحل الاسم.'],
['Networking','المنفذ 443 لا يصل لآلة. ما تسلسل فحص مناسب؟','NSG والمسار وIP والخدمة والـfirewall داخل النظام','شعار التطبيق فقط','حجم القرص فقط','عدد المستخدمين فقط','الاتصال يمر عبر طبقات شبكة وخدمة متعددة.'],
['Monitor and backup','تريد تنبيهًا عند تجاوز CPU حدًا معينًا. ما المكونات؟','Azure Monitor metric alert مع action group','Tag مع DNS','Azure Files فقط','Bicep دون مراقبة','القاعدة تحدد الشرط وaction group تحدد الإشعار.'],
['Monitor and backup','تحتاج تحليل logs بلغة استعلام. أين؟','Log Analytics workspace باستخدام KQL','Azure DNS','NSG فقط','Storage tier','workspace يجمع السجلات ويدعم KQL.'],
['Monitor and backup','ما أداة مراقبة اتصال بين VM ووجهة عبر الزمن؟','Connection monitor في Network Watcher','Azure Tags','Azure Bastion فقط','Blob lifecycle','Connection monitor يقيس اتصال الشبكة بشكل مستمر.'],
['Monitor and backup','تريد نسخ VM احتياطيًا يوميًا والاحتفاظ 30 يومًا. ما الذي تضبط؟','Vault وbackup policy ثم حماية VM','NSG فقط','Tag','VM Scale Set فقط','سياسة النسخ تحدد الجدول والاحتفاظ.'],
['Monitor and backup','ما الفرق بين Azure Backup وSite Recovery؟','الأول نسخ واستعادة بيانات والثاني تكرار وتحويل عند الكوارث','كلاهما DNS','الأول لا يدعم VM','الثاني يخزن tags','لكل منهما هدف مختلف في التعافي.'],
['Monitor and backup','تعطل إقليمي وتحتاج تشغيل workload في منطقة ثانية. ما الإجراء المخطط له؟','Failover عبر Site Recovery المُجهّز','تغيير اسم Resource group','إزالة NSG','زيادة حجم القرص فقط','Site Recovery يدعم تحويل العمل إلى موقع ثانوي.'],
['Monitor and backup','نسخ VM الاحتياطي يفشل. أين تبدأ؟','Backup jobs والتنبيهات وحالة الـvault والامتدادات','قناة Wi-Fi','شكل Tag','اسم المتصفح','سجلات المهام تحدد مرحلة الفشل.'],
['Monitor and backup','كيف تكتشف حادثة Azure تؤثر على منطقتك؟','Service Health alerts','Storage Explorer','VM size','Bicep parameters','Service Health يعرض أحداث الخدمة ذات الصلة.']
];
const az104questions=AZ104.map(([topic,text,correct,a,b,c,why])=>({topic,text,options:[correct,a,b,c],answer:0,why}));
const az104index=window.OMNITECH_EXAMS.findIndex(e=>e.id==='az-104');
window.OMNITECH_EXAMS[az104index]={id:'az-104',name:'Microsoft AZ-104 · Azure Administrator',track:'Microsoft · Azure Administration',minutes:100,questions:az104questions};
