// Original diagnostic items mapped to Cisco CCNA 200-301 v1.1 topic domains.
// Educational practice only; no Cisco exam items or official score conversion.
const CCNA_ITEMS = [
// Network Fundamentals — 20%
['Network Fundamentals','أي جهاز يوجّه الحزم بين شبكتين IP مختلفتين؟',['Router','Layer 2 switch','Hub','Repeater'],0,'التوجيه بين الشبكات وظيفة الراوتر.'],
['Network Fundamentals','سويتش Layer 2 يتخذ قرار تمرير إطار Ethernet اعتمادًا على ماذا؟',['Destination MAC','Destination TCP port','TTL','DNS name'],0,'جدول MAC يستخدم عنوان الوجهة على طبقة الربط.'],
['Network Fundamentals','أي جهاز يمد طاقة لكاميرا IP عبر كابل الشبكة مع البيانات؟',['PoE switch','Passive hub','DNS server','Media converter فقط'],0,'منفذ PoE يزوّد الجهاز بالطاقة والبيانات.'],
['Network Fundamentals','في تصميم spine-leaf، كيف يتصل كل leaf عادةً؟',['بكل spine','بـleaf واحد فقط','بالإنترنت مباشرة دون spine','بسويتش access واحد فقط'],0,'اتصال leaf بكل spine يوفر مسارات متعددة.'],
['Network Fundamentals','أي وسيط مناسب لمسافة طويلة مع حساسية أقل للتداخل الكهرومغناطيسي؟',['Single-mode fiber','UTP Cat5e','Coax قصير','USB'],0,'الألياف أحادية النمط مناسبة للمسافات الطويلة.'],
['Network Fundamentals','واجهتان Ethernet مضبوطتان: إحداهما full-duplex والأخرى half-duplex. ما العرض المتوقع؟',['تصادمات وأداء متذبذب','تحسن الأداء','توقف DNS فقط','تغير عنوان IP تلقائيًا'],0,'عدم توافق duplex يسبب أخطاء وإعادة إرسال.'],
['Network Fundamentals','تطبيق يحتاج تسليمًا مرتبًا وموثوقًا للبيانات. أي بروتوكول نقل أنسب؟',['TCP','UDP','ARP','ICMP'],0,'TCP يوفر تسلسلًا وتأكيد استلام وإعادة إرسال.'],
['Network Fundamentals','كم عنوان مضيف قابل للاستخدام في شبكة IPv4 ذات القناع /28؟',['14','16','30','6'],0,'أربعة بتات للمضيف تعطي 16 عنوانًا، 14 قابلًا للاستخدام.'],
['Network Fundamentals','ما عنوان الشبكة الذي يحتوي 192.168.10.77/26؟',['192.168.10.64','192.168.10.0','192.168.10.128','192.168.10.76'],0,'حجم الكتلة 64؛ العنوان 77 يقع بين 64 و127.'],
['Network Fundamentals','أي عنوان IPv4 من المجال الخاص؟',['172.20.4.8','172.32.4.8','11.0.0.1','169.200.1.1'],0,'172.16.0.0 إلى 172.31.255.255 مجال خاص.'],
['Network Fundamentals','أي prefix يطابق IPv6 link-local؟',['FE80::/10','2000::/3','FF00::/8','FC00::/7'],0,'عناوين link-local تقع ضمن FE80::/10.'],
['Network Fundamentals','أي prefix يُستخدم لعناوين IPv6 multicast؟',['FF00::/8','FE80::/10','::1/128','2001:db8::/32'],0,'IPv6 multicast يبدأ بـFF.'],
['Network Fundamentals','مضيف Windows يظهر IPv4 من 169.254.0.0/16 بدل العنوان المتوقع. ما الاحتمال الأول؟',['تعذر الوصول إلى DHCP','نجاح DNS','تفعيل NAT','وجود OSPF'],0,'APIPA يظهر عند تعذر الحصول على lease من DHCP.'],
['Network Fundamentals','في 2.4 GHz، أي مجموعة قنوات Wi-Fi غير متداخلة في الاستخدام الشائع بعرض 20 MHz؟',['1 و6 و11','1 و2 و3','3 و4 و5','6 و7 و8'],0,'1 و6 و11 الترتيب الشائع لتقليل التداخل.'],
['Network Fundamentals','عند استقبال سويتش إطارًا من MAC جديد، ماذا يتعلم؟',['Source MAC والمنفذ الداخل','Destination IP فقط','TTL واسم المضيف','Destination port فقط'],0,'يتعلم السويتش عنوان المصدر على المنفذ الوارد.'],
['Network Fundamentals','السويتش لا يعرف Destination MAC لإطار unicast. ماذا يفعل عادةً؟',['يفيض الإطار على منافذ VLAN عدا منفذ الدخول','يسقط الإطار دائمًا','يرسله إلى DNS','يغير عنوان المصدر'],0,'Unknown unicast يُغرق ضمن نفس VLAN.'],
['Network Fundamentals','أي عنوان IPv6 هو loopback؟',['::1','::','FF02::1','FE80::1'],0,'::1 هو عنوان loopback المحلي.'],
['Network Fundamentals','ما الفرق الأساسي بين container وVM كاملة؟',['الحاوية تشارك kernel المضيف غالبًا','الحاوية تحتاج hypervisor مستقل دائمًا','VM تشارك نفس kernel دائمًا','لا يمكن تشغيل تطبيق في حاوية'],0,'الحاويات تعزل العمليات مع مشاركة kernel المضيف عادة.'],
['Network Fundamentals','أي نطاق IPv4 يمثل شبكة /30 تحوي 10.0.0.6؟',['10.0.0.4/30','10.0.0.0/30','10.0.0.6/30','10.0.0.8/30'],0,'كتل /30 حجمها أربعة عناوين؛ 6 يقع في 4–7.'],
['Network Fundamentals','عنوان 192.0.2.9/29. ما عنوان broadcast لهذه الشبكة؟',['192.0.2.15','192.0.2.7','192.0.2.9','192.0.2.16'],0,'شبكة /29 تبدأ عند 8 وتنتهي بعنوان broadcast 15.'],
// Network Access — 20%
['Network Access','منفذ switch يصل جهاز مستخدم في VLAN 20. ما الوضع المعتاد؟',['Access VLAN 20','Trunk native VLAN 20','Routed port','SPAN destination'],0,'منفذ الجهاز النهائي يوضع عادة في access VLAN.'],
['Network Access','كيف تنقل وصلة واحدة VLAN 10 وVLAN 20 بين سويتشين؟',['802.1Q trunk','Access VLAN 10','PortFast فقط','DHCP relay'],0,'Trunk يضع علامات VLAN على الإطارات عند الحاجة.'],
['Network Access','على trunk 802.1Q افتراضي، كيف تُرسل إطارات native VLAN؟',['بدون tag عادة','بتغليف GRE','بـIPsec','تُسقط دائمًا'],0,'الـnative VLAN تمر غالبًا غير موسومة.'],
['Network Access','اختلاف native VLAN بين طرفي trunk قد يسبب ماذا؟',['تسرب حركة VLAN ومشكلات اتصال','زيادة سرعة STP','تحسين الأمان تلقائيًا','إلغاء الحاجة إلى VLAN'],0,'عدم التطابق قد يرسل حركة إلى VLAN غير مقصودة.'],
['Network Access','جهاز في VLAN 10 يريد الاتصال بجهاز في VLAN 20. ماذا يلزم؟',['توجيه بين VLANs','CDP فقط','تغيير duplex','PortFast'],0,'الاتصال بين شبكتي VLAN يحتاج Layer 3.'],
['Network Access','أي بروتوكول اكتشاف جيران متعدد الموردين؟',['LLDP','CDP','PAgP','VTP'],0,'LLDP معيار مفتوح، بينما CDP خاص بسيسكو.'],
['Network Access','أي وضعَي LACP ينشئان EtherChannel معًا؟',['Active وPassive','Passive وPassive','On وPassive','Auto وDesirable'],0,'Active يفاوض وPassive يستجيب في LACP.'],
['Network Access','لماذا يُستخدم EtherChannel؟',['تجميع وصلات متوافقة كوصلة منطقية','تحويل IPv4 إلى IPv6','تخزين كلمات المرور','إلغاء STP من كل الشبكة'],0,'يجمع روابط في port-channel لزيادة السعة والتوافر.'],
['Network Access','في STP، ما السويتش الذي يصبح Root Bridge؟',['الأقل Bridge ID','الأعلى عنوان IP','الأسرع منفذًا فقط','أول جهاز شُغّل'],0,'اختيار الجذر يعتمد على أقل Bridge ID.'],
['Network Access','على سويتش غير الجذر، ما Root Port؟',['المنفذ بأفضل مسار نحو الجذر','كل منفذ access','منفذ الإدارة فقط','المنفذ ذو VLAN الأعلى'],0,'Root Port هو أفضل مسار لذلك السويتش إلى الجذر.'],
['Network Access','أين يُفعّل PortFast عادةً؟',['منفذ متصل بجهاز نهائي','وصلة trunk إلى سويتش آخر','منفذ root بين السويتشات','منفذ uplink غير معروف'],0,'PortFast مخصص عادة لمنافذ الأجهزة النهائية.'],
['Network Access','ماذا يفعل BPDU Guard عند وصول BPDU إلى منفذ PortFast محمي؟',['يضع المنفذ في err-disabled','يغير عنوان IP','يشغل DHCP','يحذف VLAN'],0,'يحمي من توصيل سويتش غير متوقع على منفذ طرفي.'],
['Network Access','ما وظيفة Root Guard؟',['منع جار من أن يصير root عبر منفذ محمي','تشفير الترافيك','منع DHCP spoofing','منح عنوان MAC ثابت'],0,'Root Guard يحفظ موضع الجذر المتوقع.'],
['Network Access','ما الإعداد الذي يحدد VLAN صوتية لهاتف IP متصل بمنفذ access؟',['switchport voice vlan','ip helper-address','spanning-tree root primary','encapsulation dot1q على الراوتر'],0,'أمر voice vlan يعلن الشبكة الصوتية على المنفذ.'],
['Network Access','أي طريقة إدارة تشفر جلسة CLI على الشبكة؟',['SSH','Telnet','HTTP','TFTP'],0,'SSH يوفر قناة مشفرة للإدارة.'],
['Network Access','ما دور WLC في بنية Cisco wireless مركزية؟',['إدارة APs وسياسات WLAN','حل DNS لكل الإنترنت','توزيع PoE مباشرة','استبدال كل switches'],0,'المتحكم يدير نقاط الوصول والشبكات اللاسلكية.'],
['Network Access','عند إنشاء SSID مؤمن بكلمة مرور في WLC، أي إعداد يتعلق بحماية الارتباط؟',['WPA2/WPA3','NTP server','OSPF area','SNMP community'],0,'بروتوكولات WPA تضبط حماية شبكة Wi-Fi.'],
['Network Access','أي حالة RSTP تسمح بتمرير بيانات المستخدم؟',['Forwarding','Discarding','Blocking legacy فقط','Listening legacy فقط'],0,'Forwarding يمرر الإطارات ويتعلم العناوين.'],
['Network Access','كيف تتحقق من trunk والـVLANs المسموح بها على سويتش Cisco؟',['show interfaces trunk','show ip route','show version فقط','ping 127.0.0.1'],0,'الأمر يعرض منافذ trunk والـVLANs المسموح بها.'],
['Network Access','وصلتان في EtherChannel لهما إعداد VLAN مختلف. ما المتوقع؟',['قد لا تنضم إحداهما إلى الحزمة','تجمعان دائمًا دون فحص','يتغير عنوان MAC للحاسب','يتوقف DNS فقط'],0,'أعضاء port-channel تحتاج إعدادات متوافقة.'],
// IP Connectivity — 25%
['IP Connectivity','جدول التوجيه يحتوي 10.0.0.0/8 و10.2.0.0/16 و10.2.3.0/24. أي مسار لـ10.2.3.7؟',['10.2.3.0/24','10.2.0.0/16','10.0.0.0/8','Default route'],0,'Longest prefix match يختار /24.'],
['IP Connectivity','إذا وُجد مساران لنفس prefix من بروتوكولين مختلفين، ما معيار المفاضلة أولًا؟',['Administrative distance','Metric قبل AD دائمًا','عدد عناوين MAC','اسم الواجهة'],0,'بعد تساوي طول prefix تُقارن AD بين مصادر التوجيه.'],
['IP Connectivity','ما معنى Gateway of Last Resort في جدول Cisco؟',['المسار الافتراضي','عنوان WLC','الـDR في OSPF','منفذ console'],0,'هو مسار الوجهات التي لا تطابق مسارات أكثر تحديدًا.'],
['IP Connectivity','أي أمر يضيف default static route في IPv4 عبر 192.0.2.1؟',['ip route 0.0.0.0 0.0.0.0 192.0.2.1','ip route 255.255.255.255 0.0.0.0 192.0.2.1','router ospf 192.0.2.1','ip default-gateway 0.0.0.0 على راوتر مفعّل routing'],0,'0.0.0.0/0 يمثّل المسار الافتراضي.'],
['IP Connectivity','أي قناع يعبّر عن host route IPv4؟',['/32','/30','/24','/0'],0,'Host route يطابق عنوان مضيف واحدًا.'],
['IP Connectivity','ما الغرض من floating static route؟',['مسار احتياطي بـAD أعلى','توزيع DHCP','منع broadcast','زيادة أولوية route الرئيسي'],0,'تُستخدم AD أعلى ليظهر المسار عند فقد الأساسي.'],
['IP Connectivity','ما الأمر الصحيح لمسار IPv6 افتراضي عبر next hop؟',['ipv6 route ::/0 2001:db8:1::1','ip route ::/0 2001:db8:1::1','ipv6 default 0.0.0.0','router ipv6 default'],0,'صيغة IPv6 الافتراضية هي ::/0.'],
['IP Connectivity','ما شرط أساسي لتكوين OSPF adjacency بين راوترين على وصلة واحدة؟',['توافق area والعديد من معاملات الجوار','تطابق router ID','تطابق hostname','نفس default gateway'],0,'اختلاف area أو معاملات الجوار يمنع adjacency.'],
['IP Connectivity','اثنان من راوترات OSPF لديهما نفس router ID. ماذا يحدث غالبًا؟',['مشكلات في تمييز الجيران وLSA','يصبح كلاهما DR تلقائيًا','يتحولان إلى BGP','لا أثر إطلاقًا'],0,'Router ID يجب أن يكون فريدًا في نطاق OSPF.'],
['IP Connectivity','أي شبكة OSPF تختار DR وBDR عادةً؟',['Broadcast multiaccess','Point-to-point','Loopback فقط','كل واجهة passive'],0,'شبكات Ethernet broadcast تستخدم انتخاب DR/BDR.'],
['IP Connectivity','عند تساوي OSPF priority على broadcast، ما عامل كسر التعادل في DR election؟',['أعلى Router ID','أقل Router ID','أقل MAC','أعلى ASN'],0,'أعلى Router ID يحسم عند تساوي الأولوية.'],
['IP Connectivity','واجهة OSPF priority=0. ما أثره؟',['لا تُنتخب DR/BDR','لا ترسل Hello مطلقًا','تصير DR دائمًا','توقف IP routing'],0,'الأولوية صفر تمنع انتخاب الواجهة DR/BDR.'],
['IP Connectivity','ما فائدة passive-interface في OSPF على LAN مستخدمين؟',['إعلان الشبكة دون إرسال Hello عليها','حذف الشبكة من OSPF','إيقاف التوجيه كليًا','تعيين DR يدويًا'],0,'تبقى الشبكة معلنة مع منع تكوين جيران عليها.'],
['IP Connectivity','عنوان وجهة 172.16.2.5 يطابق static /24 وOSPF /16. أي مسار يستخدم؟',['Static /24','OSPF /16','الأقل metric بصرف النظر عن prefix','كلاهما'],0,'الأطول prefix يتقدم على AD حتى لو المصدر مختلف.'],
['IP Connectivity','أي حرف في جدول Cisco يشير غالبًا إلى route متصل مباشرة؟',['C','S','O','B'],0,'C = connected، S = static، O = OSPF.'],
['IP Connectivity','عنوان الوجهة لا يطابق أي route ولا يوجد default. ماذا يحدث؟',['يسقط الراوتر الحزمة','يرسلها إلى DNS','يختار أول منفذ أبجديًا','يبدل عنوان الوجهة'],0,'لا توجد معلومات تمرير للحزمة.'],
['IP Connectivity','أي هدف لـFHRP مثل HSRP؟',['توفير بوابة افتراضية متاحة عند تعطل جهاز','مزامنة NTP','تشفير VLAN','حل أسماء DNS'],0,'FHRP يوفر default gateway افتراضية مع توافر.'],
['IP Connectivity','على وصلة point-to-point، لماذا لا حاجة عادة إلى DR/BDR؟',['لا توجد شبكة متعددة الوصول تحتاج تقليل adjacency','لأن OSPF معطل','لأن IP غير مستخدم','لأنها VLAN native'],0,'الوصلة بين جارَين فقط لا تستفيد من انتخاب DR.'],
['IP Connectivity','أي أمر يعرض مسارات IPv4 على جهاز Cisco؟',['show ip route','show vlan brief','show etherchannel summary','show mac address-table'],0,'show ip route يعرض جدول توجيه IPv4.'],
['IP Connectivity','أي أمر يعرض جيران OSPFv2 الحاليين؟',['show ip ospf neighbor','show interfaces trunk','show ip nat translations','show cdp traffic'],0,'الأمر يوضح حالة جيران OSPF.'],
['IP Connectivity','في شبكة OSPF واحدة، ما أثر اختلاف hello/dead timers على الواجهتين المتجاورتين؟',['يفشل تكوين adjacency غالبًا','يزيد OSPF cost فقط','يتغير الـVLAN','يستبدل OSPF بـRIP'],0,'يجب توافق مؤقتات Hello/Dead بين الجيران.'],
['IP Connectivity','عند تكوين static route بـnext hop غير قابل للوصول، ماذا تتوقع؟',['قد لا يُثبت المسار أو لا يعمل التمرير حسب حل next hop','يتحول تلقائيًا إلى OSPF','يصبح connected','يزيد سرعة الواجهة'],0,'وصول next hop ضروري لتمرير الحزم.'],
['IP Connectivity','ما معنى OSPF cost الأصغر بين مسارين صالحين لنفس الوجهة؟',['المسار المفضل داخل OSPF','أولوية إدارية أعلى رقمًا','عدد VLAN أقل','زمن DHCP أقصر'],0,'OSPF يفضل أقل مجموع cost للمسار.'],
['IP Connectivity','ما route الذي يطابق جميع عناوين IPv6 عند عدم وجود مسار أدق؟',['::/0','::1/128','FE80::/10','FF00::/8'],0,'::/0 هو المسار الافتراضي لـIPv6.'],
['IP Connectivity','راوتر لديه مسار static بـAD 1 وOSPF بـAD 110 لنفس /24. ما المختار عند توفرهما؟',['Static','OSPF','الأعلى metric','الأحدث زمنًا'],0,'الأقل AD يربح عند تساوي طول prefix.'],
// IP Services — 10%
['IP Services','ما وظيفة NAT داخل المصدر static؟',['ربط عنوان داخلي بعنوان خارجي ثابت','اختيار DR','توزيع VLAN','تشفير SSH'],0,'Static NAT يوفر ترجمة ثابتة واحد إلى واحد.'],
['IP Services','ما فائدة DHCP relay على واجهة VLAN لا تضم خادم DHCP؟',['تمرير طلبات DHCP إلى خادم في شبكة أخرى','منح IP عشوائي دون خادم','تعطيل DNS','تحويل TCP إلى UDP'],0,'Relay يوجه بث DHCP إلى خادم بعيد.'],
['IP Services','عند حل اسم server.example إلى عنوان IP، أي خدمة تستخدم؟',['DNS','NTP','SNMP','Syslog'],0,'DNS يحل الأسماء إلى سجلات عنوان.'],
['IP Services','ما دور NTP في إدارة أجهزة الشبكة؟',['مزامنة الوقت','توزيع العناوين','تجميع الوصلات','تشفير الإطارات'],0,'توقيت موحد يساعد السجلات والتحقيقات.'],
['IP Services','أي بروتوكول يستخدم غالبًا لمراقبة counters وواجهات أجهزة الشبكة؟',['SNMP','FTP','ARP','LACP'],0,'SNMP يوفر قياسات ومعلومات إدارة.'],
['IP Services','Syslog severity 0 تعني ماذا؟',['Emergency','Debugging','Informational','Warning'],0,'الصفر أعلى درجات الخطورة في syslog.'],
['IP Services','أي تقنية QoS تحدد أو تخفف معدل المرور بتأخير الحزم في طابور؟',['Shaping','Policing بإسقاط مباشر دائمًا','NAT','DNS caching'],0,'Shaping يؤخر ويرتب الحزم وفق المعدل المحدد.'],
['IP Services','ما البروتوكول الأفضل لنقل نسخة إعدادات ببيانات اعتماد واتصال مشفر مقارنة بـTFTP؟',['SFTP/SSH','TFTP نفسه','CDP','LLDP'],0,'SFTP يعمل فوق SSH ويوفر تشفيرًا؛ TFTP بلا تشفير.'],
['IP Services','لتفعيل دخول SSH لجهاز Cisco، ما الشرط المهم؟',['مفاتيح RSA ومستخدم/اعتماد مناسب','تفعيل Telnet فقط','منع عنوان الإدارة','إزالة hostname'],0,'SSH يحتاج إعداد الهوية والمفاتيح ووسيلة اعتماد.'],
['IP Services','ما الفرق الأساسي بين policing وshaping؟',['Policing قد يسقط/يعيد تعليم الزائد، وshaping يخزن مؤقتًا','كلاهما DNS','shaping يغير MAC','policing يتطلب VLAN جديدة'],0,'shaping يستخدم طابورًا، بينما policing يفرض المعدل على المرور الزائد.'],
// Security Fundamentals — 15%
['Security Fundamentals','ما الفرق بين vulnerability وexploit؟',['الثغرة ضعف، والاستغلال طريقة لاستعماله','كلاهما اسم حساب','الثغرة حماية، والاستغلال تحديث','لا فرق'],0,'الضعف قابل للاستغلال؛ exploit هو آلية استخدامه.'],
['Security Fundamentals','أي ضبط يقلل الوصول غير المصرح إلى أجهزة الشبكة عند سرقة كلمة مرور؟',['MFA','Telnet بلا تشفير','حساب مدير مشترك','كلمة مرور واحدة لكل الأجهزة'],0,'عامل إضافي يقلل أثر كلمة مرور مسروقة.'],
['Security Fundamentals','أي بروتوكول AAA يفصل المحاسبة عن التحقق من الهوية كوظائف؟',['TACACS+ أو RADIUS','ARP','STP','CDP'],0,'AAA يشمل Authentication وAuthorization وAccounting.'],
['Security Fundamentals','ما الغرض من standard IPv4 ACL؟',['تصفية أساسًا بحسب source IP','تصفية URL كامل','تشفير HTTPS','تغيير MAC'],0,'Standard ACL تطابق عنوان المصدر IPv4.'],
['Security Fundamentals','Extended ACL يمكنها المطابقة على ماذا زيادة على standard؟',['Source/Destination IP والبروتوكول والمنافذ','اسم مستخدم Windows فقط','قوة Wi-Fi فقط','رقم VLAN فقط'],0,'Extended ACL أكثر تفصيلًا على Layer 3/4.'],
['Security Fundamentals','لماذا يُوضع permit مقصود قبل نهاية ACL؟',['لأن هناك implicit deny في النهاية','لأن كل ACL تسمح افتراضيًا','لإلغاء NAT','لتفعيل OSPF'],0,'إن لم تطابق قاعدة permit، يُرفض المرور ضمنيًا.'],
['Security Fundamentals','كيف يقلل DHCP snooping هجوم خادم DHCP مزيف؟',['يقبل ردود الخادم من منافذ trusted فقط','يزيد TTL','يلغي DNS','يمنع كل VLANs'],0,'يمنع عروض DHCP من المنافذ غير الموثوقة.'],
['Security Fundamentals','ما الذي تعتمد عليه Dynamic ARP Inspection غالبًا للتحقق من الربط؟',['DHCP snooping binding table','جدول OSPF','سجل NTP','اسم SSID'],0,'DAI يتحقق من تطابق IP/MAC عبر binding موثوق.'],
['Security Fundamentals','ما أثر port security violation في وضع shutdown؟',['وضع المنفذ err-disabled','تغيير IP الجهاز','إرسال syslog فقط مع استمرار المرور','تكوين trunk'],0,'Shutdown يغلق المنفذ عند مخالفة سياسة MAC.'],
['Security Fundamentals','أي VPN يربط شبكتَي فرعين عبر الإنترنت عادةً؟',['Site-to-site IPsec','Remote access لمستخدم واحد فقط','STP','LACP'],0,'IPsec site-to-site يحمي المرور بين الموقعين.'],
['Security Fundamentals','أي معيار لاسلكي يوفر حماية أحدث من WPA2 مع SAE في النمط الشخصي؟',['WPA3-Personal','WEP','Open','WPA الأصلي'],0,'WPA3-Personal يستخدم SAE.'],
['Security Fundamentals','ما مبدأ least privilege؟',['منح الصلاحيات اللازمة فقط','منح الجميع admin','تعطيل سجلات التدقيق','إعادة استعمال كلمة المرور'],0,'تقليل الصلاحيات يحد الضرر عند الاختراق.'],
['Security Fundamentals','في ACL على واجهة router، معنى in هو تطبيقها على المرور متى؟',['عند دخوله الواجهة قبل قرار التوجيه','بعد خروجه من الواجهة','على SSH فقط','بعد NAT دائمًا'],0,'الاتجاه in يطبق الفلترة عند استقبال الحزمة.'],
['Security Fundamentals','أي وسيلة تحمي كلمة مرور الإدارة أثناء نقلها عبر الشبكة؟',['SSH بدل Telnet','HTTP بدل HTTPS','TFTP بدل SFTP','SNMPv1 بدل SNMPv3'],0,'SSH يشفر بيانات الاعتماد والجلسة.'],
['Security Fundamentals','لماذا يعد تعطيل المنافذ غير المستخدمة ممارسة جيدة؟',['تقليل سطح الهجوم','زيادة عدد VLANs','رفع OSPF cost','تسريع DNS'],0,'المنفذ غير المستخدم النشط قد يتيح اتصالًا غير مصرح به.'],
// Automation and Programmability — 10%
['Automation and Programmability','في بنية SDN، ما وظيفة control plane؟',['اتخاذ قرارات التوجيه والسياسات','تمرير البتات في الكابل فقط','تزويد PoE','حفظ سجلات DNS فقط'],0,'control plane يحسب القرارات، وdata plane ينفذ التمرير.'],
['Automation and Programmability','أي API يتواصل غالبًا بين تطبيق خارجي وcontroller؟',['Northbound API','Southbound API','ARP','LACP'],0,'Northbound يعرض خدمات المتحكم للتطبيقات.'],
['Automation and Programmability','ما معنى underlay في شبكة overlay/underlay؟',['البنية الفيزيائية أو IP الحاملة','الشبكة الافتراضية المشفرة فقط','لوحة المستخدم','قاعدة كلمات المرور'],0,'underlay توفر الاتصال الأساسي الذي يحمل overlay.'],
['Automation and Programmability','أي HTTP method شائع لجلب مورد في REST API دون تعديله؟',['GET','POST','DELETE','PATCH'],0,'GET يُستخدم لاسترجاع المورد.'],
['Automation and Programmability','أي HTTP method شائع لحذف مورد REST؟',['DELETE','GET','HEAD','OPTIONS'],0,'DELETE يدل على طلب حذف المورد.'],
['Automation and Programmability','في JSON، أي صياغة تمثل object صحيحًا؟',['{"vlan":20,"active":true}','(vlan=20)','<vlan>20</vlan>','vlan:20;active:true'],0,'JSON object يستخدم مفاتيح بين علامات اقتباس وأقواس معقوفة.'],
['Automation and Programmability','ما فائدة Ansible في إدارة الشبكات؟',['أتمتة تنفيذ إعدادات ومهام متكررة','استبدال كل بروتوكولات التوجيه','زيادة طاقة PoE','تخصيص تردد Wi-Fi تلقائيًا دائمًا'],0,'يمكن استخدام playbooks لتنفيذ تغييرات متسقة.'],
['Automation and Programmability','ما نموذج Terraform الأساسي؟',['تعريف البنية التحتية ككود ثم تطبيق التغييرات','بروتوكول Layer 2','خادم DNS فقط','أداة لقياس طول الكابل'],0,'Terraform يعرّف الموارد declaratively ككود.'],
['Automation and Programmability','أي مثال أقرب إلى predictive AI في تشغيل الشبكة؟',['توقع ازدحام رابط من بيانات تاريخية','تغيير اسم السويتش يدويًا','استبدال الكابل بلا بيانات','توزيع IP ثابت لكل الأجهزة'],0,'النموذج التنبؤي يتعلم من بيانات ليتوقع حالة لاحقة.'],
['Automation and Programmability','لماذا يُفضَّل API بدل نسخ أوامر CLI يدويًا على مئات الأجهزة؟',['تكرار قابل للقياس والتحقق وتقليل الأخطاء','لأنه يلغي الحاجة إلى اعتماد','لأنه يمنع كل الأعطال','لأنه يغير نوع الكابل'],0,'الواجهة البرمجية تساعد الأتمتة المتسقة والتحقق من النتائج.']
];
const bank=CCNA_ITEMS.map(([topic,text,options,answer,why])=>({topic,text,options,answer,why}));
if(bank.length!==100)throw new Error(`CCNA question count: ${bank.length}`);
const ix=window.OMNITECH_EXAMS.findIndex(e=>e.id==='ccna');
if(ix<0)throw new Error('CCNA assessment missing');
window.OMNITECH_EXAMS[ix]={id:'ccna',name:'Cisco CCNA 200-301 · v1.1',track:'Enterprise Networking',minutes:120,questions:bank};
